spring:
  application:
    name: TestApplication

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: '*'
env:
 name: test        



owner:
  name: test sasmita samanta singhar
hello:
  rel: test dj
