spring:
  application:
    name: TestApplication

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: '*'
env:
 name: dev
 
owner:
  name: dev killer
hello:
  rel: dev dj
